# Generated by Django 4.2.8 on 2024-06-09 16:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='memory_state',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
