# Generated by Django 4.2.8 on 2024-06-10 20:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_chat_memory_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='json_history',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
