# Generated by Django 4.2.8 on 2024-06-20 20:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_chat_json_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='invalid_tool_calls',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chat',
            name='tool_calls',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
