# Generated by Django 4.2.8 on 2024-06-21 08:17

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_chat_invalid_tool_calls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='json_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
