# Generated by Django 4.2.8 on 2024-06-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_completionquestion_alter_toolmessage_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionquestion',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
