# Generated by Django 4.2.8 on 2024-06-21 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_completionquestion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.chat'),
        ),
    ]
