# Generated by Django 4.2.8 on 2024-06-21 21:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_basemessage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolmessage',
            name='tool_args',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
