# Generated by Django 4.2.8 on 2024-06-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_toolmessage_tool_args'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('toolmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.toolmessage')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('dashboard.toolmessage',),
        ),
    ]
