# Generated by Django 4.2.8 on 2023-12-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='description',
            field=models.TextField(verbose_name='Subject of the problem set'),
        ),
    ]
