# Generated by Django 4.2.8 on 2024-06-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_problemset_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField()),
                ('correct_choice', models.IntegerField()),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.problemset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeResponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.problemset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
