# Generated by Django 4.2.8 on 2024-06-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_freeresponsequestion_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='correct_choice',
            new_name='correct_answer',
        ),
    ]
