# Generated by Django 4.2.8 on 2024-06-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_rename_correct_choice_multiplechoicequestion_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_answer', models.CharField(max_length=100)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.problemset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
