# Generated by Django 4.2.8 on 2024-06-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_completionquestion_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='CompletionQuestionTool',
        ),
        migrations.RenameModel(
            old_name='FreeResponseQuestion',
            new_name='FreeResponseQuestionTool',
        ),
        migrations.RenameModel(
            old_name='MultipleChoiceQuestion',
            new_name='MultipleChoiceQuestionTool',
        ),
        migrations.RenameModel(
            old_name='CompletionQuestion',
            new_name='QuestionTool',
        ),
        migrations.CreateModel(
            name='LectureTool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.problemset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
