# Generated by Django 4.2.8 on 2024-06-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_rename_question_completionquestiontool_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletionQuestionTool',
            new_name='CompletionQuestion',
        ),
        migrations.RenameModel(
            old_name='FreeResponseQuestionTool',
            new_name='FreeResponseQuestion',
        ),
        migrations.RenameModel(
            old_name='LectureTool',
            new_name='GenerativeLecture',
        ),
        migrations.RenameModel(
            old_name='MultipleChoiceQuestionTool',
            new_name='MultipleChoiceQuestion',
        ),
        migrations.RenameModel(
            old_name='QuestionTool',
            new_name='Question',
        ),
    ]
