# Generated by Django 4.2.8 on 2024-06-21 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_rename_generativelecture_lecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletionQuestion',
        ),
    ]
